version: "2"

run:
  go: "1.25"
  concurrency: 4
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gosec
    - misspell
    - whitespace
    - revive
  settings:
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: true
  exclusions:
    rules:
      - path: "_test.go"
        linters:
          - revive
          - errcheck
          - gosec
