server:
    enable_embed_nats: true
    embed_nats:
        host: 127.0.0.1
        port: 4222
        store_path: ./data/nats
        max_memory: 67108864
        max_storage: 1073741824
        log_level: INFO
        write_deadline: 2s
agent:
    id: watchdog-agent
    collector:
        report_interval_sec: 10
        collect_cpu: true
        collect_memory: true
        collect_disk: true
        collect_network: true
        collect_load: true
        collect_uptime: true
    info_report_interval: 600
    heartbeat_interval: 5
storage:
    agent_bucket:
        name: wd-agents
        history: 3
        ttl: 24h0m0s
        storage: file
        replicas: 1
        compression: false
    agent_stream:
        name: wd-agents
        description: Agent communications stream
        subject_pattern: wd.a.>
        retention: limits
        max_age: 168h0m0s
        max_bytes: 104857600
        max_msgs: 100000
        storage: file
        replicas: 1
        no_ack: false
        duplicates: 5m0s
nats:
    name: natsx.client
    urls:
        - nats://localhost:4222
    token: ""
    nkey: ""
    jwt: ""
    connect_timeout: 2s
    max_reconnects: -1
    reconnect_wait: 2s
    enable_tls: false
    tls_skip_verify: false
health:
    addr: :9091
    livez_path: /livez
    readyz_path: /readyz
    metrics_path: /metrics
    metrics_namespace: ""
logger:
    console:
        enabled: true
        level: info
        format: text
    file:
        enabled: false
        level: info
        format: json
        filename: watchdog.log
        max_size: 100
        max_backups: 3
        max_age: 7
        compress: true
shutdown_timeout_sec: 10
